services:
    database:
        image: postgres
        container_name: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: rentx
        volumes:
            - postgres:/data/postgres
        networks:
            - postgres

    app:
        container_name: rentx
        build: .
        env_file:
            - prod.env
        restart: always
        ports:
            - 3333:3333
            - 9229:9229
        volumes:
            - .:/usr/app
        networks:
            - postgres
        depends_on:
            - database
networks:
    postgres:
        driver: bridge

volumes:
    postgres: